name: Build web app
description: Build web application
runs:
  using: composite

  steps:
    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Node.js dependencies
      shell: bash
      working-directory: ./src/web-app/
      run: npm ci

    - name: Install env-cmd
      shell: bash
      working-directory: ./src/web-app/
      run: npm install -g env-cmd

    - name: Run build
      shell: bash
      working-directory: ./src/web-app/
      run: npx env-cmd -f ./env.example npm run build
