# docker compose for production
version: "3"

services:
  reverse-proxy:
    restart: on-failure

    # use different image name than of the dev image
    # to avoid name conflict (now we can keep both containers locally)
    image: reverse-proxy-production
    # since the image is not available in any repository we disable pulling
    pull_policy: never

    build: ./src/reverse-proxy/production/


    ports:
      - 80:80
  mongo:
    image: mongo:4.1
    restart: always
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:

  formio:
    build: ./src/formio/
    # will restart if mongo unavailable (again a bad choice bad the form.io devs)
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    # TODO: this is horrible design by form.io, trying to communicate with them to remove this
    volumes:
      - ./src/formio/:/app:rw
    env_file:
      - ./formio.env
    stdin_open: true  # -i
    tty: true # -t

volumes:
  mongodb-data:
