# docker compose configuration for development
version: "3"

services:
  web-app:
    # use different image name than of the production image
    # to avoid name conflict (now we can keep both containers locally)
    image: web-app-dev
    # since the image is not available in any repository we disable pulling
    pull_policy: never
    build:
      context: src/web-app/
      dockerfile: Dockerfile.dev
    # container_name: web
    restart: always
    volumes:
      - ./src/web-app:/app
      # keep node_modules and .next folders in the container, rather than host
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
  reverse-proxy:
    # use different image name than of the production image
    # to avoid name conflict (now we can keep both containers locally)
    image: reverse-proxy-dev
    # since the image is not available in any repository we disable pulling
    pull_policy: never

    build: ./src/reverse-proxy/dev/

    volumes:
      - ./src/reverse-proxy/dev/nginx.conf:/etc/nginx/nginx.conf

    ports:
      - 8080:8080
  formio:
    environment:
      DEBUG: formio:*
    ports:
      - 3001:3001
  mongo:
    ports:
      - 27017:27017
  monitoring:
    ports:
      - 9090:8080
