# Use node alpine as it's a small node image
FROM node:18-alpine

# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat

# The app is going to live in /app
RUN mkdir -p /app
WORKDIR /app

# Install dependencies
COPY package*.json .
COPY prisma/schema.prisma .

RUN npm ci

# This line is necessary, because the server (npm run dev)
# will start before the mounting from host is done.
# At least some valid project files are needed to start the server.
# This seems like a weird hack, but it seems to work okay.
COPY . /app

EXPOSE 3000

CMD ["npm", "run", "dev"]
