name: Formatting checks docs

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    branches:
      - main
    paths:
      - docs/**

defaults:
  run:
    working-directory: docs

jobs:
  run-formatting-checks:
    name: Run formatting checks docs
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run formatting checks
        run: npm run format:check
